sensor:
  api:
    # host that the sensor api will bind to
    host: localhost
    # port that the sensor api will bind to
    port: 8080
    # uncomment this section to enable https with example self signed crypt material
    # https:
    #   certificate: server/test-crypt/example_cert.pem
    #   key: server/test-crypt/example_key_encrypted.pem
    #   password: examplekeypassword
  token:
    # How long issued tokens will be valid for in microseconds (28 days here)
    duration: 2419200000000
    # token signing secrets. generate them with "weaklayer-gateway secret"
    secrets:
      # REQUIRED: the current secret is used to issue and verify tokens
      current: jZAcBYO3EussMYp/GtfAx+luMZd17BQX3lgLxCGTLBY47pR2glLuC4XdUlIe70O19Uu4Yy5zqzH7aIbVQbl7cw==
      # past secrets are not used for issuing tokens but the server will accept tokens created with them
      past:
        - sQBc60569Z4mcf0Idf6OIu+u+Ht+vjz9rqQDx7/mdHUKoMWcFpvfcHRA3Ta5yB1HlHsIRkRajLtdLFmRgpwtiQ==
        - zAVlcn/qje8jAjL6HWyMZrKiKuYgLIWfVn4uHZA2KaPLbQWCII9wymJe+WPmAph2Qbau5pYDPXAzjVfYo2pU6Q==
  install:
    # verfifiers are used to verify the keys that sensors provide on installation requests
    # you can specify more than one verifier for a given group
    verifiers:
      -
        group: 68886d61-572b-41a5-8edd-93a564fb5ba3
        salt: oWrccA==
        hash: bAW4dciXby0vAAhqHDebxsLioy6H3eYzGqvL8CMRhh0=
        checksum: fhpiskuymKjvsyRKJ/U9ohdKRDpgft4x/Exn/zHM1zs=
# Destinations for the gateway to write events to
# At least one output must be present
outputs:
- type: stdout
- type: filesystem
  # the top directory where the gateway will write events to the filesystem
  directory: ./weaklayer-events
  # the time, in microseconds, that a file will be closed after
  age: 30000000
  # the size, in bytes, that a file will be closed after
  size: 10000
